CREATE TABLE E0(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE E1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE E2(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE E3(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE EC(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE SP1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE SP2(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE D1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE D2(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE F1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE F2(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE I1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE I2(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE P1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE N1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE B1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE T1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE G1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE SC0(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE SC1(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE SC2(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE SC3(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE ALLMATCHES(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE ALLTEAMS(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,FTHG INTEGER,FTAG INTEGER,FTR TEXT,HTHG INTEGER,HTAG INTEGER,HTR TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE points_e0(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_e1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_e2(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_e3(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_ec(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_sp1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_sp2(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_d1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_d2(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_f1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_f2(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_i1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_i2(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_p1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_n1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_b1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_g1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_t1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_sc0(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_sc1(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_sc2(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_sc3(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE points_allteams(Team text,H_wins integer,A_wins integer,Draws integer,HG integer,AG integer,TP integer,total_points integer,goal_diff integer);
CREATE TABLE fixtures(division TEXT,Date Date,HomeTeam TEXT,AwayTeam TEXT,PSH REAL,PSD REAL,PSA REAL);
CREATE TABLE leagues(d_vision TEXT,GP INTEGER,T_HG INTEGER,T_AG INTEGER);
CREATE TABLE teams(team TEXT,team_HG INTEGER,team_homeGP INTEGER,team_AG INTEGER,team_awayGP INTEGER,team_HC INTEGER,team_AC INTEGER);

