#! /bin/bash
sed -i '1,$d' eoib.sql
sed -i '1,$d' e1ib.sql
sed -i '1,$d' e2ib.sql
sed -i '1,$d' e3ib.sql
sed -i '1,$d' ecib.sql
sed -i '1,$d' sp1ib.sql
sed -i '1,$d' sp2ib.sql
sed -i '1,$d' d1ib.sql
sed -i '1,$d' d2ib.sql
sed -i '1,$d' f1ib.sql
sed -i '1,$d' f2ib.sql
sed -i '1,$d' i1ib.sql
sed -i '1,$d' i2ib.sql
sed -i '1,$d' p1ib.sql
sed -i '1,$d' n1ib.sql
sed -i '1,$d' b1ib.sql
sed -i '1,$d' t1ib.sql
sed -i '1,$d' g1ib.sql
sed -i '1,$d' sc0ib.sql
sed -i '1,$d' sc1ib.sql
sed -i '1,$d' sc2ib.sql
sed -i '1,$d' sc3ib.sql
sed -i '1,$d' fixtures.sql
sed -i '1,$d' INSERTALL.sql
sed -i '1,$d' htcs.txt
sed -i '1,$d' cs.txt
sed -i '1,$d' tempallmatches0.txt
sed -i '1,$d' tempallmatches1.txt
sed -i '1,$d' tempallmatches2.txt
sed -i '2,$d' allmatches.txt
