INSERT INTO G1 VALUES('<html><head>','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('<title>300 Multiple Choices</title>','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('</head><body>','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('<h1>Multiple Choices</h1>','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('The document name you requested (<code>/mmz4281/2122/G1.csv</code>) could not be found on this server.','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('However',' we found documents with names similar to the one you requested.<p>Available documents:','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('<ul>','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('<li><a href="/mmz4281/2122/B1.csv">/mmz4281/2122/B1.csv</a> (mistyped character)','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('<li><a href="/mmz4281/2122/F1.csv">/mmz4281/2122/F1.csv</a> (mistyped character)','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('<li><a href="/mmz4281/2122/E1.csv">/mmz4281/2122/E1.csv</a> (mistyped character)','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('<li><a href="/mmz4281/2122/P1.csv">/mmz4281/2122/P1.csv</a> (mistyped character)','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('<li><a href="/mmz4281/2122/D1.csv">/mmz4281/2122/D1.csv</a> (mistyped character)','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('<li><a href="/mmz4281/2122/N1.csv">/mmz4281/2122/N1.csv</a> (mistyped character)','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('<li><a href="/mmz4281/2122/T1.csv">/mmz4281/2122/T1.csv</a> (mistyped character)','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('</ul>','','','','','','','','','','','','','','','','','','','','');
INSERT INTO G1 VALUES('</body></html>','','','','','','','','','','','','','','','','','','','','');
