INSERT INTO I1 VALUES('<html><head>','','','','','','','','','','','','');
INSERT INTO I1 VALUES('<title>300 Multiple Choices</title>','','','','','','','','','','','','');
INSERT INTO I1 VALUES('</head><body>','','','','','','','','','','','','');
INSERT INTO I1 VALUES('<h1>Multiple Choices</h1>','','','','','','','','','','','','');
INSERT INTO I1 VALUES('The document name you requested (<code>/mmz4281/1819/I1.csv</code>) could not be found on this server.','','','','','','','','','','','','');
INSERT INTO I1 VALUES('However',' we found documents with names similar to the one you requested.<p>Available documents:','','','','','','','','','','','');
INSERT INTO I1 VALUES('<ul>','','','','','','','','','','','','');
INSERT INTO I1 VALUES('<li><a href="/mmz4281/1819/B1.csv">/mmz4281/1819/B1.csv</a> (mistyped character)','','','','','','','','','','','','');
INSERT INTO I1 VALUES('<li><a href="/mmz4281/1819/E1.csv">/mmz4281/1819/E1.csv</a> (mistyped character)','','','','','','','','','','','','');
INSERT INTO I1 VALUES('<li><a href="/mmz4281/1819/F1.csv">/mmz4281/1819/F1.csv</a> (mistyped character)','','','','','','','','','','','','');
INSERT INTO I1 VALUES('<li><a href="/mmz4281/1819/T1.csv">/mmz4281/1819/T1.csv</a> (mistyped character)','','','','','','','','','','','','');
INSERT INTO I1 VALUES('<li><a href="/mmz4281/1819/P1.csv">/mmz4281/1819/P1.csv</a> (mistyped character)','','','','','','','','','','','','');
INSERT INTO I1 VALUES('<li><a href="/mmz4281/1819/N1.csv">/mmz4281/1819/N1.csv</a> (mistyped character)','','','','','','','','','','','','');
INSERT INTO I1 VALUES('</ul>','','','','','','','','','','','','');
INSERT INTO I1 VALUES('</body></html>','','','','','','','','','','','','');
