INSERT INTO I2 VALUES('<html><head>','','','','','','','','','','','','');
INSERT INTO I2 VALUES('<title>300 Multiple Choices</title>','','','','','','','','','','','','');
INSERT INTO I2 VALUES('</head><body>','','','','','','','','','','','','');
INSERT INTO I2 VALUES('<h1>Multiple Choices</h1>','','','','','','','','','','','','');
INSERT INTO I2 VALUES('The document name you requested (<code>/mmz4281/1819/I2.csv</code>) could not be found on this server.','','','','','','','','','','','','');
INSERT INTO I2 VALUES('However',' we found documents with names similar to the one you requested.<p>Available documents:','','','','','','','','','','','');
INSERT INTO I2 VALUES('<ul>','','','','','','','','','','','','');
INSERT INTO I2 VALUES('<li><a href="/mmz4281/1819/F2.csv">/mmz4281/1819/F2.csv</a> (mistyped character)','','','','','','','','','','','','');
INSERT INTO I2 VALUES('<li><a href="/mmz4281/1819/E2.csv">/mmz4281/1819/E2.csv</a> (mistyped character)','','','','','','','','','','','','');
INSERT INTO I2 VALUES('<li><a href="/mmz4281/1819/D2.csv">/mmz4281/1819/D2.csv</a> (mistyped character)','','','','','','','','','','','','');
INSERT INTO I2 VALUES('</ul>','','','','','','','','','','','','');
INSERT INTO I2 VALUES('</body></html>','','','','','','','','','','','','');
