#! /bin/bash 
cat eoib.sql > INSERTALL.sql 
cat e1ib.sql >> INSERTALL.sql 
cat e2ib.sql >> INSERTALL.sql 
cat e3ib.sql >> INSERTALL.sql 
cat ecib.sql >> INSERTALL.sql 
cat sp1ib.sql >> INSERTALL.sql 
cat sp2ib.sql >> INSERTALL.sql 
cat d1ib.sql >> INSERTALL.sql 
cat d2ib.sql >> INSERTALL.sql 
cat f1ib.sql >> INSERTALL.sql 
cat f2ib.sql >> INSERTALL.sql 
cat i1ib.sql >> INSERTALL.sql 
cat i2ib.sql >> INSERTALL.sql 
cat p1ib.sql >> INSERTALL.sql 
cat n1ib.sql >> INSERTALL.sql 
cat b1ib.sql >> INSERTALL.sql 
cat t1ib.sql >> INSERTALL.sql 
cat g1ib.sql >> INSERTALL.sql 
cat sc0ib.sql >> INSERTALL.sql 
cat sc1ib.sql >> INSERTALL.sql 
cat sc2ib.sql >> INSERTALL.sql 
cat sc3ib.sql >> INSERTALL.sql
#cat fixtures.sql >> INSERTALL.sql
