update points_e0 set H_wins=(select count(*) from E0 where HomeTeam=Team and FTR='H');
update points_e1 set H_wins=(select count(*) from E1 where HomeTeam=Team and FTR='H');
update points_e2 set H_wins=(select count(*) from E2 where HomeTeam=Team and FTR='H');
update points_e3 set H_wins=(select count(*) from E3 where HomeTeam=Team and FTR='H');
update points_ec set H_wins=(select count(*) from EC where HomeTeam=Team and FTR='H');
update points_sp1 set H_wins=(select count(*) from SP1 where HomeTeam=Team and FTR='H');
update points_sp2 set H_wins=(select count(*) from SP2 where HomeTeam=Team and FTR='H');
update points_d1 set H_wins=(select count(*) from D1 where HomeTeam=Team and FTR='H');
update points_d2 set H_wins=(select count(*) from D2 where HomeTeam=Team and FTR='H');
update points_f1 set H_wins=(select count(*) from F1 where HomeTeam=Team and FTR='H');
update points_f2 set H_wins=(select count(*) from F2 where HomeTeam=Team and FTR='H');
update points_i1 set H_wins=(select count(*) from I1 where HomeTeam=Team and FTR='H');
update points_i2 set H_wins=(select count(*) from I2 where HomeTeam=Team and FTR='H');
update points_p1 set H_wins=(select count(*) from P1 where HomeTeam=Team and FTR='H');
update points_n1 set H_wins=(select count(*) from N1 where HomeTeam=Team and FTR='H');
update points_b1 set H_wins=(select count(*) from B1 where HomeTeam=Team and FTR='H');
update points_t1 set H_wins=(select count(*) from T1 where HomeTeam=Team and FTR='H');
update points_g1 set H_wins=(select count(*) from G1 where HomeTeam=Team and FTR='H');
update points_sc0 set H_wins=(select count(*) from SC0 where HomeTeam=Team and FTR='H');
update points_sc1 set H_wins=(select count(*) from SC1 where HomeTeam=Team and FTR='H');
update points_sc2 set H_wins=(select count(*) from SC2 where HomeTeam=Team and FTR='H');
update points_sc3 set H_wins=(select count(*) from SC3 where HomeTeam=Team and FTR='H');
update points_allteams set H_wins=(select count(*) from ALLTEAMS where HomeTeam=Team and FTR='H');
update points_e0 set HG=(select count(*) from E0 where HomeTeam=Team );
update points_e1 set HG=(select count(*) from E1 where HomeTeam=Team );
update points_e2 set HG=(select count(*) from E2 where HomeTeam=Team );
update points_e3 set HG=(select count(*) from E3 where HomeTeam=Team );
update points_ec set HG=(select count(*) from EC where HomeTeam=Team );
update points_sp1 set HG=(select count(*) from SP1 where HomeTeam=Team );
update points_sp2 set HG=(select count(*) from SP2 where HomeTeam=Team );
update points_d1 set HG=(select count(*) from D1 where HomeTeam=Team );
update points_d2 set HG=(select count(*) from D2 where HomeTeam=Team );
update points_f1 set HG=(select count(*) from F1 where HomeTeam=Team );
update points_f2 set HG=(select count(*) from F2 where HomeTeam=Team );
update points_i1 set HG=(select count(*) from I1 where HomeTeam=Team );
update points_i2 set HG=(select count(*) from I2 where HomeTeam=Team );
update points_p1 set HG=(select count(*) from P1 where HomeTeam=Team );
update points_n1 set HG=(select count(*) from N1 where HomeTeam=Team );
update points_b1 set HG=(select count(*) from B1 where HomeTeam=Team );
update points_t1 set HG=(select count(*) from T1 where HomeTeam=Team );
update points_g1 set HG=(select count(*) from G1 where HomeTeam=Team );
update points_sc0 set HG=(select count(*) from SC0 where HomeTeam=Team );
update points_sc1 set HG=(select count(*) from SC1 where HomeTeam=Team );
update points_sc2 set HG=(select count(*) from SC2 where HomeTeam=Team );
update points_sc3 set HG=(select count(*) from SC3 where HomeTeam=Team );
update points_allteams set HG=(select count(*) from ALLTEAMS where HomeTeam=Team );
update points_e0 set A_wins=(select count(*) from E0 where AwayTeam=Team and FTR='A');
update points_e1 set A_wins=(select count(*) from E1 where AwayTeam=Team and FTR='A');
update points_e2 set A_wins=(select count(*) from E2 where AwayTeam=Team and FTR='A');
update points_e3 set A_wins=(select count(*) from E3 where AwayTeam=Team and FTR='A');
update points_ec set A_wins=(select count(*) from EC where AwayTeam=Team and FTR='A');
update points_sp1 set A_wins=(select count(*) from SP1 where AwayTeam=Team and FTR='A');
update points_sp2 set A_wins=(select count(*) from SP2 where AwayTeam=Team and FTR='A');
update points_d1 set A_wins=(select count(*) from D1 where AwayTeam=Team and FTR='A');
update points_d2 set A_wins=(select count(*) from D2 where AwayTeam=Team and FTR='A');
update points_f1 set A_wins=(select count(*) from F1 where AwayTeam=Team and FTR='A');
update points_f2 set A_wins=(select count(*) from F2 where AwayTeam=Team and FTR='A');
update points_i1 set A_wins=(select count(*) from I1 where AwayTeam=Team and FTR='A');
update points_i2 set A_wins=(select count(*) from I2 where AwayTeam=Team and FTR='A');
update points_p1 set A_wins=(select count(*) from P1 where AwayTeam=Team and FTR='A');
update points_n1 set A_wins=(select count(*) from N1 where AwayTeam=Team and FTR='A');
update points_b1 set A_wins=(select count(*) from B1 where AwayTeam=Team and FTR='A');
update points_t1 set A_wins=(select count(*) from T1 where AwayTeam=Team and FTR='A');
update points_g1 set A_wins=(select count(*) from G1 where AwayTeam=Team and FTR='A');
update points_sc0 set A_wins=(select count(*) from SC0 where AwayTeam=Team and FTR='A');
update points_sc1 set A_wins=(select count(*) from SC1 where AwayTeam=Team and FTR='A');
update points_sc2 set A_wins=(select count(*) from SC2 where AwayTeam=Team and FTR='A');
update points_sc3 set A_wins=(select count(*) from SC3 where AwayTeam=Team and FTR='A');
update points_allteams set A_wins=(select count(*) from ALLTEAMS where AwayTeam=Team and FTR='A');
update points_e0 set AG=(select count(*) from E0 where AwayTeam=Team );
update points_e1 set AG=(select count(*) from E1 where AwayTeam=Team );
update points_e2 set AG=(select count(*) from E2 where AwayTeam=Team );
update points_e3 set AG=(select count(*) from E3 where AwayTeam=Team );
update points_ec set AG=(select count(*) from EC where AwayTeam=Team );
update points_sp1 set AG=(select count(*) from SP1 where AwayTeam=Team );
update points_sp2 set AG=(select count(*) from SP2 where AwayTeam=Team );
update points_d1 set AG=(select count(*) from D1 where AwayTeam=Team );
update points_d2 set AG=(select count(*) from D2 where AwayTeam=Team );
update points_f1 set AG=(select count(*) from F1 where AwayTeam=Team );
update points_f2 set AG=(select count(*) from F2 where AwayTeam=Team );
update points_i1 set AG=(select count(*) from I1 where AwayTeam=Team );
update points_i2 set AG=(select count(*) from I2 where AwayTeam=Team );
update points_p1 set AG=(select count(*) from P1 where AwayTeam=Team );
update points_n1 set AG=(select count(*) from N1 where AwayTeam=Team );
update points_b1 set AG=(select count(*) from B1 where AwayTeam=Team );
update points_t1 set AG=(select count(*) from T1 where AwayTeam=Team );
update points_g1 set AG=(select count(*) from G1 where AwayTeam=Team );
update points_sc0 set AG=(select count(*) from SC0 where AwayTeam=Team );
update points_sc1 set AG=(select count(*) from SC1 where AwayTeam=Team );
update points_sc2 set AG=(select count(*) from SC2 where AwayTeam=Team );
update points_sc3 set AG=(select count(*) from SC3 where AwayTeam=Team );
update points_allteams set AG=(select count(*) from ALLTEAMS where AwayTeam=Team );
update points_e0 set Draws=(select count(*) from E0 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_e1 set Draws=(select count(*) from E1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_e2 set Draws=(select count(*) from E2 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_e3 set Draws=(select count(*) from E3 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_ec set Draws=(select count(*) from EC where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_sp1 set Draws=(select count(*) from SP1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_sp2 set Draws=(select count(*) from SP2 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_d1 set Draws=(select count(*) from D1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_d2 set Draws=(select count(*) from D2 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_f1 set Draws=(select count(*) from F1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_f2 set Draws=(select count(*) from F2 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_i1 set Draws=(select count(*) from I1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_i2 set Draws=(select count(*) from I2 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_p1 set Draws=(select count(*) from P1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_n1 set Draws=(select count(*) from N1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_b1 set Draws=(select count(*) from B1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_t1 set Draws=(select count(*) from T1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_g1 set Draws=(select count(*) from G1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_sc0 set Draws=(select count(*) from SC0 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_sc1 set Draws=(select count(*) from SC1 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_sc2 set Draws=(select count(*) from SC2 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_sc3 set Draws=(select count(*) from SC3 where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_allteams set Draws=(select count(*) from ALLTEAMS where HomeTeam=Team and FTR='D' or AwayTeam=Team and FTR='D');
update points_e0 set TP=(HG + AG);
update points_e1 set TP=(HG + AG);
update points_e2 set TP=(HG + AG);
update points_e3 set TP=(HG + AG);
update points_ec set TP=(HG + AG);
update points_sp1 set TP=(HG + AG);
update points_sp2 set TP=(HG + AG);
update points_d1 set TP=(HG + AG);
update points_d2 set TP=(HG + AG);
update points_f1 set TP=(HG + AG);
update points_f2 set TP=(HG + AG);
update points_i1 set TP=(HG + AG);
update points_i2 set TP=(HG + AG);
update points_p1 set TP=(HG + AG);
update points_n1 set TP=(HG + AG);
update points_b1 set TP=(HG + AG);
update points_t1 set TP=(HG + AG);
update points_g1 set TP=(HG + AG);
update points_sc0 set TP=(HG + AG);
update points_sc1 set TP=(HG + AG);
update points_sc2 set TP=(HG + AG);
update points_sc3 set TP=(HG + AG);
update points_allteams set TP=(HG + AG);
update points_e0 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_e1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_e2 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_e3 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_ec set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_sp1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_sp2 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_d1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_d2 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_f1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_f2 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_i1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_i2 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_p1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_n1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_b1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_t1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_g1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_sc0 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_sc1 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_sc2 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_sc3 set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_allteams set total_points=(H_wins + A_wins)*3 + Draws*1;
update points_e0 set goal_diff=((select sum(FTHG) from E0 where HomeTeam=Team) + (select sum(FTAG) from E0 where AwayTeam=Team)) - ((select sum(FTAG)from E0 where HomeTeam=Team) +  (select sum(FTHG) from E0 where AwayTeam=Team));
update points_e1 set goal_diff=((select sum(FTHG) from E1 where HomeTeam=Team) + (select sum(FTAG) from E1 where AwayTeam=Team)) - ((select sum(FTAG)from E1 where HomeTeam=Team) +  (select sum(FTHG) from E1 where AwayTeam=Team));
update points_e2 set goal_diff=((select sum(FTHG) from E2 where HomeTeam=Team) + (select sum(FTAG) from E2 where AwayTeam=Team)) - ((select sum(FTAG)from E2 where HomeTeam=Team) +  (select sum(FTHG) from E2 where AwayTeam=Team));
update points_e3 set goal_diff=((select sum(FTHG) from E3 where HomeTeam=Team) + (select sum(FTAG) from E3 where AwayTeam=Team)) - ((select sum(FTAG)from E3 where HomeTeam=Team) +  (select sum(FTHG) from E3 where AwayTeam=Team));
update points_ec set goal_diff=((select sum(FTHG) from EC where HomeTeam=Team) + (select sum(FTAG) from EC where AwayTeam=Team)) - ((select sum(FTAG)from EC where HomeTeam=Team) +  (select sum(FTHG) from EC where AwayTeam=Team));
update points_sp1 set goal_diff=((select sum(FTHG) from SP1 where HomeTeam=Team) + (select sum(FTAG) from SP1 where AwayTeam=Team)) - ((select sum(FTAG)from SP1 where HomeTeam=Team) +  (select sum(FTHG) from SP1 where AwayTeam=Team));
update points_sp2 set goal_diff=((select sum(FTHG) from SP2 where HomeTeam=Team) + (select sum(FTAG) from SP2 where AwayTeam=Team)) - ((select sum(FTAG)from SP2 where HomeTeam=Team) +  (select sum(FTHG) from SP2 where AwayTeam=Team));
update points_d1 set goal_diff=((select sum(FTHG) from D1 where HomeTeam=Team) + (select sum(FTAG) from D1 where AwayTeam=Team)) - ((select sum(FTAG)from D1 where HomeTeam=Team) +  (select sum(FTHG) from D1 where AwayTeam=Team));
update points_d2 set goal_diff=((select sum(FTHG) from D2 where HomeTeam=Team) + (select sum(FTAG) from D2 where AwayTeam=Team)) - ((select sum(FTAG)from D2 where HomeTeam=Team) +  (select sum(FTHG) from D2 where AwayTeam=Team));
update points_f1 set goal_diff=((select sum(FTHG) from F1 where HomeTeam=Team) + (select sum(FTAG) from F1 where AwayTeam=Team)) - ((select sum(FTAG)from F1 where HomeTeam=Team) +  (select sum(FTHG) from F1 where AwayTeam=Team));
update points_f2 set goal_diff=((select sum(FTHG) from F2 where HomeTeam=Team) + (select sum(FTAG) from F2 where AwayTeam=Team)) - ((select sum(FTAG)from F2 where HomeTeam=Team) +  (select sum(FTHG) from F2 where AwayTeam=Team));
update points_i1 set goal_diff=((select sum(FTHG) from I1 where HomeTeam=Team) + (select sum(FTAG) from I1 where AwayTeam=Team)) - ((select sum(FTAG)from I1 where HomeTeam=Team) +  (select sum(FTHG) from I1 where AwayTeam=Team));
update points_i2 set goal_diff=((select sum(FTHG) from I2 where HomeTeam=Team) + (select sum(FTAG) from I2 where AwayTeam=Team)) - ((select sum(FTAG)from I2 where HomeTeam=Team) +  (select sum(FTHG) from I2 where AwayTeam=Team));
update points_p1 set goal_diff=((select sum(FTHG) from P1 where HomeTeam=Team) + (select sum(FTAG) from P1 where AwayTeam=Team)) - ((select sum(FTAG)from P1 where HomeTeam=Team) +  (select sum(FTHG) from P1 where AwayTeam=Team));
update points_n1 set goal_diff=((select sum(FTHG) from N1 where HomeTeam=Team) + (select sum(FTAG) from N1 where AwayTeam=Team)) - ((select sum(FTAG)from N1 where HomeTeam=Team) +  (select sum(FTHG) from N1 where AwayTeam=Team));
update points_b1 set goal_diff=((select sum(FTHG) from B1 where HomeTeam=Team) + (select sum(FTAG) from B1 where AwayTeam=Team)) - ((select sum(FTAG)from B1 where HomeTeam=Team) +  (select sum(FTHG) from B1 where AwayTeam=Team));
update points_t1 set goal_diff=((select sum(FTHG) from T1 where HomeTeam=Team) + (select sum(FTAG) from T1 where AwayTeam=Team)) - ((select sum(FTAG)from T1 where HomeTeam=Team) +  (select sum(FTHG) from T1 where AwayTeam=Team));
update points_g1 set goal_diff=((select sum(FTHG) from G1 where HomeTeam=Team) + (select sum(FTAG) from G1 where AwayTeam=Team)) - ((select sum(FTAG)from G1 where HomeTeam=Team) +  (select sum(FTHG) from G1 where AwayTeam=Team));
update points_sc0 set goal_diff=((select sum(FTHG) from SC0 where HomeTeam=Team) + (select sum(FTAG) from SC0 where AwayTeam=Team)) - ((select sum(FTAG)from SC0 where HomeTeam=Team) +  (select sum(FTHG) from SC0 where AwayTeam=Team));
update points_sc1 set goal_diff=((select sum(FTHG) from SC1 where HomeTeam=Team) + (select sum(FTAG) from SC1 where AwayTeam=Team)) - ((select sum(FTAG)from SC1 where HomeTeam=Team) +  (select sum(FTHG) from SC1 where AwayTeam=Team));
update points_sc2 set goal_diff=((select sum(FTHG) from SC2 where HomeTeam=Team) + (select sum(FTAG) from SC2 where AwayTeam=Team)) - ((select sum(FTAG)from SC2 where HomeTeam=Team) +  (select sum(FTHG) from SC2 where AwayTeam=Team));
update points_sc3 set goal_diff=((select sum(FTHG) from SC3 where HomeTeam=Team) + (select sum(FTAG) from SC3 where AwayTeam=Team)) - ((select sum(FTAG)from SC3 where HomeTeam=Team) +  (select sum(FTHG) from SC3 where AwayTeam=Team));
update points_allteams set goal_diff=((select sum(FTHG) from ALLTEAMS where HomeTeam=Team) + (select sum(FTAG) from ALLTEAMS where AwayTeam=Team)) - ((select sum(FTAG)from ALLTEAMS where HomeTeam=Team) +  (select sum(FTHG) from ALLTEAMS where AwayTeam=Team));
